name: reserve_for_you_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.`
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  http: ^0.13.3
  lottie: ^1.0.1
  smooth_page_indicator: ^0.2.3
  shared_preferences: ^2.0.5
  syncfusion_localizations: ^19.2.46
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  connectivity: ^3.0.3
  device_info: ^2.0.0
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.0
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.4
  google_places_picker: ^3.0.2
  geocoder: ^0.2.1
  url_launcher: ^6.0.6
  flutter_html:
  flutter_stripe: ^2.4.0
  flutter_webview_plugin:
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  permission_handler: ^8.0.0+2
  image_viewer:
  image_picker: ^0.8.0+1
  pull_to_refresh: ^2.0.0
  sign_in_with_apple: ^3.2.0
  the_apple_sign_in: ^1.1.1
  syncfusion_flutter_calendar: ^19.4.40
  readmore: ^2.1.0
  flutter_staggered_grid_view: ^0.4.0
  colorful_safe_area: ^0.3.0
  maps_launcher: ^2.0.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.5
  image_downloader: ^0.30.0
  provider: ^6.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  pinput: ^1.2.2
  webview_flutter_plus: ^0.2.3
  pay: ^1.0.6
  network_to_file_image: ^3.1.0
  path_provider: ^2.0.9
  flutter_pay: ^1.0.2
  intl_phone_field: ^3.1.0
  twilio_flutter: ^0.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/images/
    - assets/images/Intro/
    - assets/images/Login/
    - assets/images/Category/
    - assets/images/Favourite/
    - assets/images/HomeView/
    - assets/images/DetailScreen/
    - assets/images/Confirmed/
    - assets/images/bottomnavbar/
    - assets/images/Profile/
    - assets/images/Settings/
    - assets/images/GiveFeedback/
    - assets/
  
    
  
  fonts:
    - family: CAMPTONBLACK
      fonts:
        - asset: assets/fonts/CAMPTON-BLACK.TTF
    - family: CAMPTONBOLD
      fonts:
        - asset: assets/fonts/CAMPTON-BOLD.TTF
    - family: CAMPTONBOOK
      fonts:
        - asset: assets/fonts/CAMPTON-BOOK.OTF
    - family: CAMPTONMEDIUM
      fonts:
        - asset: assets/fonts/CAMPTON-MEDIUM.TTF
    - family: CAMPTONSEMIBOLD
      fonts:
        - asset: assets/fonts/CAMPTON-SEMIBOLD.TTF
    - family: CAMPTONLIGHT
      fonts:
        - asset: assets/fonts/CAMPTON-LIGHT.TTF


